### ISSUE TITLE
Add please the keyboard layout image to the README doc

### ISSUE THREAD

**Issue by Yunir** [mansayk/Tatar-keyboard-layout-macOS#2]
Something like this:

**Comment by Yunir** [comment]
![Uploading image.png…]()

**Comment by Yunir** [comment]
Captured from the settings of MacOS
![image](https://user-images.githubusercontent.com/16368046/94476468-3265de80-01d9-11eb-8860-62bd84f63814.png)

**Comment by mansayk** [comment]
Thank you very much, Yunir! 
I used your captured image there, it looks well!
Next time you can make a pull request ;)
